#LSTM model
LSTMArgs:
        dataset_path: '../0003d-DBAASP-Database/Database_of_Antimicrobial_Activity_and_structure_of_Peptides'
        output_size: 22
        epochs: 50
        batch_size: 256
        learning_rate: 0.00063
        hidden_size: 256
        layers: 2
        dropout: 0.7
        max_length: 15
        vocab: ['R', 'H', 'K', 'D', 'E', 'S', 'T', 'N', 'Q', 'C','G', 'P', 'A', 'I', 'L', 'M', 'F', 'W', 'Y', 'V', '_']
        save_model: True
        model_path: 'lstm_peptides_model.pt'

#Generation file
LSTMArgsGen:
        dataset_path: '../0003d-DBAASP-Database/Database_of_Antimicrobial_Activity_and_structure_of_Peptides'
        output_path: '../0006b-LSTM-data/generation_peptides.fasta'
        output_size: 22
        epochs: 50
        batch_size: 256
        learning_rate: 0.00063
        hidden_size: 256
        layers: 2
        dropout: 0.7
        save_model: False
        temperature: 1.0
        num_sequences: 100
        min_length: 2
        max_length: 15
        seed: 'r'

#AMP sorting
SortingArgs:
        input_path: '../0006b-LSTM-data/generation_peptides.fasta'
        sorting_path: '../0006b-LSTM-data/sorted_peptides.fasta'
        output_path: '../0006b-LSTM-data/potential_amp.fasta'

#MIC prediction
MICArgs:
          data_path: "../0003e-DRAMP-MIC-database/DRAMP_MIC_p_aeruginosa.csv"
          batch_size: 8
          epochs: 50
          embedding_dim: 100
          hidden_dim: 256
          num_layers: 2
          dropout: 0.5
          learning_rate: 0.001
          weight_decay: 0.00001
          max_seq_len: 15
          accuracy_percentage: 10.0
          train_ratio: 0.8
          vocab_size: 21
          train: true
          model_path: "bi_lstm_peptides_model.pt"
          peptide_path: "../0006b-LSTM-data/sorted_peptides.fasta"
          prediction_path: "../0006b-LSTM-data/predictions.csv"