_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.0
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": darwin-x86_64
batch_size:
    value: 4
dropout:
    value: 0.5
epochs:
    value: 50
hidden size:
    value: 256
layers:
    value: 2
learning rate:
    value: 0.01
output size:
    value: 22
