#!/bin/bash
gmx grompp -f production_umbrella.mdp -c conf1.gro -p topol.top -r conf1.gro -n index.ndx -o umbrella0.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf3.gro -p topol.top -r conf3.gro -n index.ndx -o umbrella1.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf5.gro -p topol.top -r conf5.gro -n index.ndx -o umbrella2.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf7.gro -p topol.top -r conf7.gro -n index.ndx -o umbrella3.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf9.gro -p topol.top -r conf9.gro -n index.ndx -o umbrella4.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf11.gro -p topol.top -r conf11.gro -n index.ndx -o umbrella5.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf13.gro -p topol.top -r conf13.gro -n index.ndx -o umbrella6.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf15.gro -p topol.top -r conf15.gro -n index.ndx -o umbrella7.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf17.gro -p topol.top -r conf17.gro -n index.ndx -o umbrella8.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf19.gro -p topol.top -r conf19.gro -n index.ndx -o umbrella9.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf21.gro -p topol.top -r conf21.gro -n index.ndx -o umbrella10.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf23.gro -p topol.top -r conf23.gro -n index.ndx -o umbrella11.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf25.gro -p topol.top -r conf25.gro -n index.ndx -o umbrella12.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf27.gro -p topol.top -r conf27.gro -n index.ndx -o umbrella13.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf29.gro -p topol.top -r conf29.gro -n index.ndx -o umbrella14.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf31.gro -p topol.top -r conf31.gro -n index.ndx -o umbrella15.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf33.gro -p topol.top -r conf33.gro -n index.ndx -o umbrella16.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf35.gro -p topol.top -r conf35.gro -n index.ndx -o umbrella17.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf37.gro -p topol.top -r conf37.gro -n index.ndx -o umbrella18.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf39.gro -p topol.top -r conf39.gro -n index.ndx -o umbrella19.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf41.gro -p topol.top -r conf41.gro -n index.ndx -o umbrella20.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf43.gro -p topol.top -r conf43.gro -n index.ndx -o umbrella21.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf45.gro -p topol.top -r conf45.gro -n index.ndx -o umbrella22.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf47.gro -p topol.top -r conf47.gro -n index.ndx -o umbrella23.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf49.gro -p topol.top -r conf49.gro -n index.ndx -o umbrella24.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf51.gro -p topol.top -r conf51.gro -n index.ndx -o umbrella25.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf53.gro -p topol.top -r conf53.gro -n index.ndx -o umbrella26.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf55.gro -p topol.top -r conf55.gro -n index.ndx -o umbrella27.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf57.gro -p topol.top -r conf57.gro -n index.ndx -o umbrella28.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf59.gro -p topol.top -r conf59.gro -n index.ndx -o umbrella29.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf61.gro -p topol.top -r conf61.gro -n index.ndx -o umbrella30.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf63.gro -p topol.top -r conf63.gro -n index.ndx -o umbrella31.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf65.gro -p topol.top -r conf65.gro -n index.ndx -o umbrella32.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf67.gro -p topol.top -r conf67.gro -n index.ndx -o umbrella33.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf69.gro -p topol.top -r conf69.gro -n index.ndx -o umbrella34.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf71.gro -p topol.top -r conf71.gro -n index.ndx -o umbrella35.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf73.gro -p topol.top -r conf73.gro -n index.ndx -o umbrella36.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf75.gro -p topol.top -r conf75.gro -n index.ndx -o umbrella37.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf77.gro -p topol.top -r conf77.gro -n index.ndx -o umbrella38.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf79.gro -p topol.top -r conf79.gro -n index.ndx -o umbrella39.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf81.gro -p topol.top -r conf81.gro -n index.ndx -o umbrella40.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf83.gro -p topol.top -r conf83.gro -n index.ndx -o umbrella41.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf85.gro -p topol.top -r conf85.gro -n index.ndx -o umbrella42.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf87.gro -p topol.top -r conf87.gro -n index.ndx -o umbrella43.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf89.gro -p topol.top -r conf89.gro -n index.ndx -o umbrella44.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf91.gro -p topol.top -r conf91.gro -n index.ndx -o umbrella45.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf93.gro -p topol.top -r conf93.gro -n index.ndx -o umbrella46.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf95.gro -p topol.top -r conf95.gro -n index.ndx -o umbrella47.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf97.gro -p topol.top -r conf97.gro -n index.ndx -o umbrella48.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf99.gro -p topol.top -r conf99.gro -n index.ndx -o umbrella49.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf101.gro -p topol.top -r conf101.gro -n index.ndx -o umbrella50.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf103.gro -p topol.top -r conf103.gro -n index.ndx -o umbrella51.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf105.gro -p topol.top -r conf105.gro -n index.ndx -o umbrella52.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf107.gro -p topol.top -r conf107.gro -n index.ndx -o umbrella53.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf109.gro -p topol.top -r conf109.gro -n index.ndx -o umbrella54.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf111.gro -p topol.top -r conf111.gro -n index.ndx -o umbrella55.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf113.gro -p topol.top -r conf113.gro -n index.ndx -o umbrella56.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf115.gro -p topol.top -r conf115.gro -n index.ndx -o umbrella57.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf117.gro -p topol.top -r conf117.gro -n index.ndx -o umbrella58.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf119.gro -p topol.top -r conf119.gro -n index.ndx -o umbrella59.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf121.gro -p topol.top -r conf121.gro -n index.ndx -o umbrella60.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf123.gro -p topol.top -r conf123.gro -n index.ndx -o umbrella61.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf125.gro -p topol.top -r conf125.gro -n index.ndx -o umbrella62.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf127.gro -p topol.top -r conf127.gro -n index.ndx -o umbrella63.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf129.gro -p topol.top -r conf129.gro -n index.ndx -o umbrella64.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf131.gro -p topol.top -r conf131.gro -n index.ndx -o umbrella65.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf133.gro -p topol.top -r conf133.gro -n index.ndx -o umbrella66.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf135.gro -p topol.top -r conf135.gro -n index.ndx -o umbrella67.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf137.gro -p topol.top -r conf137.gro -n index.ndx -o umbrella68.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf139.gro -p topol.top -r conf139.gro -n index.ndx -o umbrella69.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf141.gro -p topol.top -r conf141.gro -n index.ndx -o umbrella70.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf143.gro -p topol.top -r conf143.gro -n index.ndx -o umbrella71.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf145.gro -p topol.top -r conf145.gro -n index.ndx -o umbrella72.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf147.gro -p topol.top -r conf147.gro -n index.ndx -o umbrella73.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf149.gro -p topol.top -r conf149.gro -n index.ndx -o umbrella74.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf151.gro -p topol.top -r conf151.gro -n index.ndx -o umbrella75.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf153.gro -p topol.top -r conf153.gro -n index.ndx -o umbrella76.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf155.gro -p topol.top -r conf155.gro -n index.ndx -o umbrella77.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf157.gro -p topol.top -r conf157.gro -n index.ndx -o umbrella78.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf159.gro -p topol.top -r conf159.gro -n index.ndx -o umbrella79.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf161.gro -p topol.top -r conf161.gro -n index.ndx -o umbrella80.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf163.gro -p topol.top -r conf163.gro -n index.ndx -o umbrella81.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf165.gro -p topol.top -r conf165.gro -n index.ndx -o umbrella82.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf167.gro -p topol.top -r conf167.gro -n index.ndx -o umbrella83.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf169.gro -p topol.top -r conf169.gro -n index.ndx -o umbrella84.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf171.gro -p topol.top -r conf171.gro -n index.ndx -o umbrella85.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf173.gro -p topol.top -r conf173.gro -n index.ndx -o umbrella86.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf175.gro -p topol.top -r conf175.gro -n index.ndx -o umbrella87.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf177.gro -p topol.top -r conf177.gro -n index.ndx -o umbrella88.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf179.gro -p topol.top -r conf179.gro -n index.ndx -o umbrella89.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf181.gro -p topol.top -r conf181.gro -n index.ndx -o umbrella90.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf183.gro -p topol.top -r conf183.gro -n index.ndx -o umbrella91.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf185.gro -p topol.top -r conf185.gro -n index.ndx -o umbrella92.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf187.gro -p topol.top -r conf187.gro -n index.ndx -o umbrella93.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf189.gro -p topol.top -r conf189.gro -n index.ndx -o umbrella94.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf191.gro -p topol.top -r conf191.gro -n index.ndx -o umbrella95.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf193.gro -p topol.top -r conf193.gro -n index.ndx -o umbrella96.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf195.gro -p topol.top -r conf195.gro -n index.ndx -o umbrella97.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf197.gro -p topol.top -r conf197.gro -n index.ndx -o umbrella98.tpr -maxwarn 2
gmx grompp -f production_umbrella.mdp -c conf199.gro -p topol.top -r conf199.gro -n index.ndx -o umbrella99.tpr -maxwarn 2
