#!/bin/bash
gmx mdrun -deffnm umbrella0
gmx mdrun -deffnm umbrella1
gmx mdrun -deffnm umbrella2
gmx mdrun -deffnm umbrella3
gmx mdrun -deffnm umbrella4
gmx mdrun -deffnm umbrella5
gmx mdrun -deffnm umbrella6
gmx mdrun -deffnm umbrella7
gmx mdrun -deffnm umbrella8
gmx mdrun -deffnm umbrella9
gmx mdrun -deffnm umbrella10
gmx mdrun -deffnm umbrella11
gmx mdrun -deffnm umbrella12
gmx mdrun -deffnm umbrella13
gmx mdrun -deffnm umbrella14
gmx mdrun -deffnm umbrella15
gmx mdrun -deffnm umbrella16
gmx mdrun -deffnm umbrella17
gmx mdrun -deffnm umbrella18
gmx mdrun -deffnm umbrella19
gmx mdrun -deffnm umbrella20
gmx mdrun -deffnm umbrella21
gmx mdrun -deffnm umbrella22
gmx mdrun -deffnm umbrella23
gmx mdrun -deffnm umbrella24
gmx mdrun -deffnm umbrella25
gmx mdrun -deffnm umbrella26
gmx mdrun -deffnm umbrella27
gmx mdrun -deffnm umbrella28
gmx mdrun -deffnm umbrella29
gmx mdrun -deffnm umbrella30
gmx mdrun -deffnm umbrella31
gmx mdrun -deffnm umbrella32
gmx mdrun -deffnm umbrella33
gmx mdrun -deffnm umbrella34
gmx mdrun -deffnm umbrella35
gmx mdrun -deffnm umbrella36
gmx mdrun -deffnm umbrella37
gmx mdrun -deffnm umbrella38
gmx mdrun -deffnm umbrella39
gmx mdrun -deffnm umbrella40
gmx mdrun -deffnm umbrella41
gmx mdrun -deffnm umbrella42
gmx mdrun -deffnm umbrella43
gmx mdrun -deffnm umbrella44
gmx mdrun -deffnm umbrella45
gmx mdrun -deffnm umbrella46
gmx mdrun -deffnm umbrella47
gmx mdrun -deffnm umbrella48
gmx mdrun -deffnm umbrella49
gmx mdrun -deffnm umbrella50
gmx mdrun -deffnm umbrella51
gmx mdrun -deffnm umbrella52
gmx mdrun -deffnm umbrella53
gmx mdrun -deffnm umbrella54
gmx mdrun -deffnm umbrella55
gmx mdrun -deffnm umbrella56
gmx mdrun -deffnm umbrella57
gmx mdrun -deffnm umbrella58
gmx mdrun -deffnm umbrella59
gmx mdrun -deffnm umbrella60
gmx mdrun -deffnm umbrella61
gmx mdrun -deffnm umbrella62
gmx mdrun -deffnm umbrella63
gmx mdrun -deffnm umbrella64
gmx mdrun -deffnm umbrella65
gmx mdrun -deffnm umbrella66
gmx mdrun -deffnm umbrella67
gmx mdrun -deffnm umbrella68
gmx mdrun -deffnm umbrella69
gmx mdrun -deffnm umbrella70
gmx mdrun -deffnm umbrella71
gmx mdrun -deffnm umbrella72
gmx mdrun -deffnm umbrella73
gmx mdrun -deffnm umbrella74
gmx mdrun -deffnm umbrella75
gmx mdrun -deffnm umbrella76
gmx mdrun -deffnm umbrella77
gmx mdrun -deffnm umbrella78
gmx mdrun -deffnm umbrella79
gmx mdrun -deffnm umbrella80
gmx mdrun -deffnm umbrella81
gmx mdrun -deffnm umbrella82
gmx mdrun -deffnm umbrella83
gmx mdrun -deffnm umbrella84
gmx mdrun -deffnm umbrella85
gmx mdrun -deffnm umbrella86
gmx mdrun -deffnm umbrella87
gmx mdrun -deffnm umbrella88
gmx mdrun -deffnm umbrella89
gmx mdrun -deffnm umbrella90
gmx mdrun -deffnm umbrella91
gmx mdrun -deffnm umbrella92
gmx mdrun -deffnm umbrella93
gmx mdrun -deffnm umbrella94
gmx mdrun -deffnm umbrella95
gmx mdrun -deffnm umbrella96
gmx mdrun -deffnm umbrella97
gmx mdrun -deffnm umbrella98
gmx mdrun -deffnm umbrella99
