#!/bin/bash
#PBS -l walltime=23:58:00
 # Two minutes to midnight. HX1 has 24hr and 48hr queues.
#PBS -l select=1:ncpus=64:mpiprocs=64:mem=500gb

# Collect node statistics
echo
echo "Jarv's node statistics: "
echo -n "Number of CPUs: " && nproc
echo -n "CPU model: " && lscpu | awk '/Model name:/ { print $0 }'
echo -n "Total memory reported to PBS: " && echo "$PBS_VMEM" | sed 's/kb//'
echo -n "Available memory (/proc/meminfo): " && grep -oP '^MemAvailable:\s*\K\d+' /proc/meminfo
echo -n "Node name: " && hostname
echo -n "Linux kernel version: " && uname -r
echo -n "Distribution: " && cat /etc/*-release | grep PRETTY_NAME | sed 's/PRETTY_NAME=//' | sed 's/"//g'
echo -n "Uptime: " && uptime -p
echo

cd $PBS_O_WORKDIR

module purge

module load GROMACS/2024.1-foss-2023b

gmx mdrun -s *.tpr

# Don't forget to include the 'hx' queue in your qsub: qsub -q hx

