_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 256
dropout:
    value: 0.5
epochs:
    value: 100
hidden_size:
    value: 128
layers:
    value: 3
learning_rate:
    value: 0.00063
output_size:
    value: 21
